In [1]:
import numpy as np

In [2]:
l1 = [12,234,34,34,-53453,343]

In [3]:
l1.pop()

343

In [4]:
l1

[12, 234, 34, 34, -53453]

In [5]:
a1 = np.array(l1)

In [6]:
a1

array([    12,    234,     34,     34, -53453])

In [7]:
a1.mean()

-10627.8

In [8]:
l2 = [23,23.4,45,43,342.55]

In [9]:
a2 = np.array(l2)

In [10]:
a2

array([ 23.  ,  23.4 ,  45.  ,  43.  , 342.55])

In [11]:
l2 = [23.78,23.4,45,43.56,342.55]

In [12]:
a3 = np.array(l2)

In [13]:
a3

array([ 23.78,  23.4 ,  45.  ,  43.56, 342.55])

In [14]:
#slicing

In [15]:
l2

[23.78, 23.4, 45, 43.56, 342.55]

In [18]:
a2[2:4:2]

array([45.])

In [19]:
b = a2[2:]

In [20]:
b

array([ 45.  ,  43.  , 342.55])

In [21]:
b[:] = 999

In [22]:
b

array([999., 999., 999.])

In [24]:
a2

array([ 23. ,  23.4, 999. , 999. , 999. ])